/**
 * A WireGuard tunnel (peer) managed by the VPS control plane.
 * Created via the dashboard and proxied to the VPS control plane API.
 */
export interface Tunnel {
  /** Unique tunnel identifier (e.g., "tun_abc123"). */
  id: string;

  /** WireGuard public key of the peer. */
  publicKey: string;

  /** Assigned VPN IP address on the WireGuard interface (e.g., "10.0.0.2"). */
  vpnIp: string;

  /** Domains associated with this tunnel for L4 routing. */
  domains: string[];

  /** Whether the tunnel is enabled. Disabled tunnels are removed from WireGuard by the reconciler. */
  enabled: boolean;

  /** Last known endpoint IP:port of the peer (updated from the WireGuard kernel). Null if never connected. */
  endpoint: string | null;

  /** ISO 8601 timestamp of the last successful WireGuard handshake. Null if never connected. */
  lastHandshake: string | null;

  /** Total bytes transmitted to the peer. */
  txBytes: number;

  /** Total bytes received from the peer. */
  rxBytes: number;

  /** Per-tunnel key rotation policy. */
  rotationPolicy: RotationPolicy;

  /** ISO 8601 timestamp of the last key rotation. Null if never rotated. */
  lastRotationAt: string | null;

  /** If a rotation is in progress, the ID of the new pending peer. Null otherwise. */
  pendingRotationId: string | null;

  /** ISO 8601 timestamp of when the tunnel was created. */
  createdAt: string;

  /** ISO 8601 timestamp of the last update. */
  updatedAt: string;
}

/**
 * WireGuard client configuration text, generated by the VPS control plane.
 * Delivered to the user once and then purged from server memory.
 */
export interface TunnelConfig {
  /** The full WireGuard .conf file contents. */
  configText: string;

  /** URL to fetch the QR code PNG (one-time use). */
  qrCodeUrl: string;

  /** The VPS WireGuard server public key. */
  serverPublicKey: string;

  /** Warning message to display to the user about saving the config. */
  warning: string;
}

/**
 * Peer connectivity status derived from WireGuard kernel state.
 */
export interface PeerStatus {
  /** Whether the peer is currently connected (handshake within last 5 minutes). */
  connected: boolean;

  /** ISO 8601 timestamp of the last successful WireGuard handshake. Null if never connected. */
  lastHandshake: string | null;

  /** Total bytes transmitted to the peer. */
  txBytes: number;

  /** Total bytes received from the peer. */
  rxBytes: number;

  /** Last known endpoint IP:port. Null if never connected. */
  endpoint: string | null;
}

/**
 * Per-tunnel key rotation policy.
 *
 * WireGuard has no in-band key renegotiation. Rotating a PSK or keypair
 * causes tunnel downtime until the user re-imports the new config.
 * WireGuard's Noise protocol already rotates session keys every ~2 minutes,
 * so long-term key rotation is only needed for compliance or compromise response.
 */
export interface RotationPolicy {
  /**
   * Whether to automatically rotate the pre-shared key on a schedule.
   * Off by default because it causes tunnel downtime until the user re-imports config.
   */
  autoRotatePsk: boolean;

  /**
   * Number of days between automatic PSK rotations.
   * Only applies when autoRotatePsk is true. 0 means disabled.
   */
  pskRotationIntervalDays: number;

  /**
   * Whether to automatically revoke peers that have been inactive
   * (no successful handshake) for longer than inactiveExpiryDays.
   */
  autoRevokeInactive: boolean;

  /**
   * Number of days of inactivity before a peer is automatically revoked.
   * Only applies when autoRevokeInactive is true.
   */
  inactiveExpiryDays: number;

  /**
   * After a key rotation, the old peer config remains active for this many minutes.
   * This gives the user time to download and re-import the new config.
   */
  gracePeriodMinutes: number;
}
